openapi: 3.0.0
info:
  title: Logística API
  version: 1.0.0
paths:
  /api/auth/register:
    post:
      summary: Registra um novo motorista
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                matricula:
                  type: string
                senha:
                  type: string
      responses:
        201:
          description: Usuário criado com sucesso
        400:
          description: Matrícula já existe ou dados inválidos

  /api/auth/login:
    post:
      summary: Login do motorista
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                matricula:
                  type: string
                senha:
                  type: string
      responses:
        200:
          description: JWT retornado com sucesso
        401:
          description: Credenciais inválidas
